### PR TITLE
Feature/card 1g user auth

### PR DESCRIPTION
**Pull request by ErikGraciosa**
Added UserService with attaching cookie,

added packages for bcryptjs": "^2.4.3",
"pug": "^3.0.0",
"jsonwebtoken": "^8.5.1",
    "md5": "^2"
cookie-parser": "^1.4.5",.3.0",

### CODE REVIEW

**Comment by ErikGraciosa** [comment]
removing because yml needs updated with env variables

**Comment by ErikGraciosa** [comment]
updated yml now and passing jest tests on github

**Review by kevinfiero — APPROVED** [review]
Looks like some good cookies were added

**Review by jeffIrvine — APPROVED** [review]
Looks good

**Pull request merged**
